version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args: [
        "--init"
      ]
    volumes:
      - ..:/workspace:cached
      - ~/.Xauthority:/root/.Xauthority
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    platform: linux/amd64
    environment:
      - DISPLAY=$DISPLAY_MAC
