version: "3.8"

services:
  ruse:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args: [
        "--init"
      ]
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    environment:
      - DISPLAY=$DISPLAY_MAC
